In [23]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from src.embedding_generation.embedding_generator import *
from src.common.logger import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
model = "BAAI/bge-small-en-v1.5"
DATASET_ENTITY_COUNT = 20000
DATASET_BASE_PATH = f"/Users/yavuz/data/LAION-{DATASET_ENTITY_COUNT}/"

METADATA_PATH = DATASET_BASE_PATH + "metadata.parquet"
vector_path = DATASET_BASE_PATH + "vectors/"

if not os.path.exists(vector_path):
    print("Creating path", vector_path)
    os.makedirs(vector_path)

Creating path /Users/yavuz/data/LAION-20000/vectors/


In [3]:
df = pd.read_parquet(METADATA_PATH)
texts = list(df["TEXT"])

In [4]:
embedding_generator: EmbeddingGenerator = SentenceTransformerEmbeddingGenerator(model)
embeddings = embedding_generator.generate_text_embeddings(texts, True)
embeddings

Loading model BAAI/bge-small-en-v1.5...
Use pytorch device_name: cpu
Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
Loaded BAAI/bge-small-en-v1.5
Generating 12788 embeddings...
Batches: 100%|██████████| 400/400 [01:36<00:00,  4.16it/s]
Done


array([[-0.05945515,  0.00921903,  0.00678941, ..., -0.04180149,
         0.01217372,  0.10467765],
       [-0.05608249, -0.02341046,  0.01316727, ..., -0.0419376 ,
        -0.05870903,  0.04695863],
       [-0.07713753, -0.02388584,  0.01643499, ..., -0.09213278,
         0.01431111,  0.00712732],
       ...,
       [-0.00355132, -0.00170841,  0.00310336, ..., -0.00858116,
        -0.01528757,  0.06652694],
       [-0.0534179 , -0.04777579,  0.02079356, ...,  0.01117438,
         0.0247307 , -0.00606936],
       [ 0.03280438, -0.01097846,  0.02551886, ..., -0.04210055,
        -0.01878911,  0.03959527]], dtype=float32)

In [5]:
np.save(vector_path+"text_vectors", embeddings)

In [6]:
#Test read
read_embeddings = np.load(vector_path+"text_vectors.npy")
read_embeddings

array([[-0.05945515,  0.00921903,  0.00678941, ..., -0.04180149,
         0.01217372,  0.10467765],
       [-0.05608249, -0.02341046,  0.01316727, ..., -0.0419376 ,
        -0.05870903,  0.04695863],
       [-0.07713753, -0.02388584,  0.01643499, ..., -0.09213278,
         0.01431111,  0.00712732],
       ...,
       [-0.00355132, -0.00170841,  0.00310336, ..., -0.00858116,
        -0.01528757,  0.06652694],
       [-0.0534179 , -0.04777579,  0.02079356, ...,  0.01117438,
         0.0247307 , -0.00606936],
       [ 0.03280438, -0.01097846,  0.02551886, ..., -0.04210055,
        -0.01878911,  0.03959527]], dtype=float32)

In [24]:
openai_embedding_generator = OpenAIEmbeddingGenerator()

In [25]:
sentences = ["hello I am dude", "bye dude"]
embeds = openai_embedding_generator.generate_text_embeddings(sentences)

Generating 2 embeddings...
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Done


In [26]:
embeds

array([[-0.00282051, -0.06312851, -0.03829524, ...,  0.00907664,
        -0.02740838,  0.00776358],
       [ 0.02286716, -0.0170915 , -0.07431518, ...,  0.01292707,
        -0.01716587,  0.05785578]])

In [18]:
a = np.array(embeds.data[0].embedding)

In [19]:
b = np.array(embeds.data[1].embedding)

In [20]:
a@b

0.6433357118144377

In [22]:
for i in embeds.data:
    print(1)

1
1
